// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZAOClSc4Bqzdk89mzwLMqj8eDmOiZ-XI',
    appId: '1:900843589568:web:538b21ef2d0536ca240225',
    messagingSenderId: '900843589568',
    projectId: 'ecomerce-f3240',
    authDomain: 'ecomerce-f3240.firebaseapp.com',
    storageBucket: 'ecomerce-f3240.firebasestorage.app',
    measurementId: 'G-DX9FX4M9D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx-7elW02napzcUYz6zjmkD9Pfp9UVMGI',
    appId: '1:900843589568:android:111c86ead9ef88b0240225',
    messagingSenderId: '900843589568',
    projectId: 'ecomerce-f3240',
    storageBucket: 'ecomerce-f3240.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqMuUJx2ve9BIZFoD5B0Gmxzx1bovtRVE',
    appId: '1:900843589568:ios:761c6eef6ce5a605240225',
    messagingSenderId: '900843589568',
    projectId: 'ecomerce-f3240',
    storageBucket: 'ecomerce-f3240.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqMuUJx2ve9BIZFoD5B0Gmxzx1bovtRVE',
    appId: '1:900843589568:ios:761c6eef6ce5a605240225',
    messagingSenderId: '900843589568',
    projectId: 'ecomerce-f3240',
    storageBucket: 'ecomerce-f3240.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZAOClSc4Bqzdk89mzwLMqj8eDmOiZ-XI',
    appId: '1:900843589568:web:f65a7dadf969cacb240225',
    messagingSenderId: '900843589568',
    projectId: 'ecomerce-f3240',
    authDomain: 'ecomerce-f3240.firebaseapp.com',
    storageBucket: 'ecomerce-f3240.firebasestorage.app',
    measurementId: 'G-H4T4H2QHFC',
  );
}
